### PR TITLE
Small fixes and design changes to filters.

### PR DESCRIPTION
**Pull request by redndahead**
# READY FOR REVIEW

# Summary
- [RHW-55: Use an Amazon S3 bucket to pull results for service catalog and Training and Workshops. This speeds up the page loading and helps when working in gitpod.](https://github.com/gsb-library/gsb_research_hub_subtheme/pull/46)
- [RHW-47: Remove the question mark at the end of the url if no filters are selected.](https://github.com/gsb-library/gsb_research_hub_subtheme/pull/47)
- [RHW-59: Allow the header to be sticky for smaller resolutions.](https://github.com/gsb-library/gsb_research_hub_subtheme/pull/48)
- [RHW-60: Accessibility fixes.](https://github.com/gsb-library/gsb_research_hub_subtheme/pull/49)
- [RHW-57: Improve the default pages and building example pages when deploying to gitpod](https://github.com/gsb-library/gsb_research_hub_subtheme/pull/50)
- [RHW-58: Adjust the design of the filters.](https://github.com/gsb-library/gsb_research_hub_subtheme/pull/51)

# Review By (Date)
- When does this need to be reviewed by? Whenever you can

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- 4

# Urgency
- How urgent is this? (Normal, High) Normal

# Review Tasks

## Setup tasks and/or behavior to test

See PR's above.

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory? No

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by buttonwillowsix** [comment]
@rebeccahongsf any chance you might have time this week to review this PR?

**Comment by buttonwillowsix** [comment]
@redndahead the sticky header at smaller resolutions is cool!

The cards don't look so good at two across:

Screenshot 2024-08-27 at 10 25 49 AM

**Comment by buttonwillowsix** [comment]
Not sure that keyboard nav is working as expected for the services catalog, but other than that and the card rendering issue, looks OK to me.

**Review by buttonwillowsix — COMMENTED** [review]
I left some comments about the card images and keyboard navigation. Looks OK to me aside from that, but I am not the right person to review the connection stuff in here, which is why I asked @rebeccahongsf to take a quick look.

**Comment by redndahead** [comment]
@buttonwillowsix The card issue is a known issue and requires a page refresh. We'll continue to work on that.

We'll add a task in our system for the keyboard navigation.

Looking forward to seeing this committed.

**Comment by jenbreese** [comment]
@redndahead I looked at the site.  
Here is what I found:
1. The labels on the cards aren't accessible by keyboard. A simple fix would be to change the `span` to a `button`. Then add `line-height: 1.5;` to get the same height as before.
2. The cards adjust again after resizing and reload. 

Both @rebeccahongsf and I looked and think it looks good.

**Review by jenbreese — APPROVED** [review]
I approve the changes.  We looked at it.  There is just the card display and making those spans accessible with a keyboard.

**Pull request merged**
