### PR TITLE
Additional theme fixes for tags in airtable pages

### PR DESCRIPTION
**Pull request by redndahead**
# READY FOR REVIEW

# Summary
- [RHW-50: Style filter tag on Training and Service Catalog pages](https://github.com/gsb-library/gsb_research_hub_subtheme/pull/43)
- [RHW-52: Add support for adding classes to arrays through the config](https://github.com/gsb-library/gsb_research_hub_subtheme/pull/42)

# Review By (Date)
- ASAP

# Criticality
- 9

# Urgency
- How urgent is this? HIGH

# Review Tasks

## Setup tasks and/or behavior to test

Review links to PR's

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?
No

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by redndahead** [comment]
@sherakama @jenbreese I don't know why it wants all the commits again that were just merged in, but we really only have 2 different PR's from what you have just merged in.

**Comment by sherakama** [comment]
@redndahead 

There are no changes in this PR to review. Did you forget to add them? 

The commits you are seeing are there as the last PR was 'squashed and merged' so you'll need to update your fork's main branch.

**Comment by redndahead** [comment]
@sherakama I have ran a sync and it says, "This branch is not behind the upstream", but yet it still allowed me to create a PR. I'm looking through main and it does seem to have our latest code. I'm a little confused on how to move forward. While we are matching it still thinks there are differences and I can create a PR.

**Comment by sherakama** [comment]
Which commits or commit range should this PR be showing?

**Comment by redndahead** [comment]
@sherakama every commit from https://github.com/SU-SWS/gsb_research_hub_subtheme/pull/24/commits/ca3fb6507a657cdd473151337b1b39f9f8126c5c on.

**Comment by sherakama** [comment]
The [last pull request](https://github.com/SU-SWS/gsb_research_hub_subtheme/pull/23/commits) was merged at https://github.com/SU-SWS/gsb_research_hub_subtheme/pull/23/commits/7b6649938058f03f3cd43417e1cb9f219daa43f4  which includes all the commits from https://github.com/SU-SWS/gsb_research_hub_subtheme/commit/ca3fb6507a657cdd473151337b1b39f9f8126c5c

The commits in the PR was squashed so all of those commits were merged into one https://github.com/SU-SWS/gsb_research_hub_subtheme/commit/717faddfc85eee7194859f9173ee0a6228f7c8ac

Your forked branch `main` still has the commit history of the squashed commits so that is why we are seeing a list of commits but no changes to review.

Is there code that is missing from the SU-SWS main branch?

**Comment by redndahead** [comment]
@sherakama I think I see all the commits, but my concern is when I go to do another PR it's going to want to have all these commits in it. I'm trying to figure out how to have everything in sync. If we merged this PR would it affect anything? I think it would at least have my main and this main more in sync.

**Comment by redndahead** [comment]
I'm open to adjusting my repo in some way so we don't have this issue. I just don't know what I should do.

**Comment by sherakama** [comment]
Aye, sorry for the confusion I've caused on this one. I usually default to squash and merge but probably should have just merged this and kept the history of your fork intact. A couple of options for the workflow going forward

1. Merge this PR to re-sync your forked branch's git history with the main repo's git history. Future PRs would be `merge commits` and not `squashed` or `rebased`.

2. Since all the work is in the SU-SWS main branch, the commit history from the fork can be forgotten. You can throw out your main branch and fetch and pull the main from SU-SWS fresh. You can also [fetch from upstream and rebase](https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github) on your forked branch. 

I'd recommend going with option 1 as that will keep things simple for everyone. No more squashing. The git history gets a lot more 'verbose' but that is probably fine in this case. 

Thoughts and preferences?

**Comment by redndahead** [comment]
I agree that we should do number 1. I think while our tree may not look pretty during this timeframe, it's the easiest to move forward.

**Comment by sherakama** [comment]
History has been added. No code changes. 
https://github.com/SU-SWS/gsb_research_hub_subtheme/compare/v1.1.1...main

**Comment by redndahead** [comment]
Thank you. It looks like we are all synced up.

**Pull request merged**
