### PR TITLE
Quote style, banner variants, external link icon

### PR DESCRIPTION
**Pull request by redndahead**
# READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- [Create quote style. ](https://github.com/gsb-library/gsb_research_hub_subtheme/pull/12)
- [Add banner style variants.](https://github.com/gsb-library/gsb_research_hub_subtheme/pull/13/)
- [Add external link icon.](https://github.com/gsb-library/gsb_research_hub_subtheme/pull/14)

# Review By (Date)
- As soon as your available

# Criticality
- Development not high criticality

# Urgency
Normal

# Review Tasks

## Setup tasks and/or behavior to test

View the pull request linked in the summary for the information.

### Site Configuration Sync

No

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Review by jenbreese — APPROVED** [review]
GTG

**Comment by redndahead** [comment]
@jenbreese It seems you approved the quote style, but this was never merged in. So I merged another branch into our main and now this PR has been updated. Add banner style variants needs to be reviewed.

**Comment by redndahead** [comment]
Added external link icon for main menu as well.

**Review by jenbreese — APPROVED** [review]
GTG

**Pull request merged**
